// Generated by tools/art/build_character_art.py from the approved art parts. Do not edit by hand.
//
// For each atlas frame: where its (trimmed) image starts inside the original art part, and its
// size, in source-art pixels. `textureScale` is atlas pixels per source-art pixel.

export interface AtlasFrameData {
  x: number;
  y: number;
  width: number;
  height: number;
}

export const PRANKSTER_ATLAS_DATA = {
  textureScale: 0.148189,
  frames: {
    arm_alt_left_lower: { x: 0.0, y: 148.46, width: 114.72, height: 188.95 },
    arm_alt_right_lower: { x: 0.0, y: 155.21, width: 114.72, height: 188.95 },
    arm_front_left: { x: 0.0, y: 0.0, width: 148.46, height: 344.16 },
    arm_front_right: { x: 0.0, y: 0.0, width: 155.21, height: 344.16 },
    head_back: { x: 0.0, y: 0.0, width: 229.44, height: 290.17 },
    head_front_mischief: { x: 0.0, y: 0.0, width: 249.68, height: 290.17 },
    head_front_shocked: { x: 0.0, y: 0.0, width: 242.93, height: 290.17 },
    head_front_smile: { x: 0.0, y: 0.0, width: 263.18, height: 296.92 },
    pants_back_L: { x: 0.0, y: 0.0, width: 141.71, height: 472.37 },
    pants_back_R: { x: 107.97, y: 0.0, width: 236.19, height: 472.37 },
    pants_back_hip: { x: 13.5, y: 0.0, width: 236.19, height: 148.46 },
    pants_front_L: { x: 0.0, y: 0.0, width: 249.68, height: 465.62 },
    pants_front_R: { x: 215.94, y: 0.0, width: 188.95, height: 465.62 },
    pants_front_hip: { x: 101.22, y: 0.0, width: 256.43, height: 141.71 },
    torso_back: { x: 0.0, y: 0.0, width: 317.16, height: 317.16 },
    torso_front_body: { x: 26.99, y: 0.0, width: 283.42, height: 303.67 },
  },
} as const satisfies { textureScale: number; frames: Record<string, AtlasFrameData> };

export const SLEEPER_ATLAS_DATA = {
  textureScale: 0.36,
  frames: {
    arm_over_head: { x: 0.0, y: 0.0, width: 280.56, height: 288.89 },
    blanket_topdown: { x: 0.0, y: 8.33, width: 941.67, height: 997.22 },
    head_annoyed: { x: 0.0, y: 0.0, width: 330.56, height: 322.22 },
    head_peeking: { x: 0.0, y: 0.0, width: 347.22, height: 327.78 },
    head_sleepy: { x: 0.0, y: 0.0, width: 352.78, height: 333.33 },
    head_snoring: { x: 0.0, y: 0.0, width: 352.78, height: 308.33 },
    head_startled: { x: 0.0, y: 0.0, width: 372.22, height: 327.78 },
    snore_bubble: { x: 0.0, y: 0.0, width: 183.33, height: 122.22 },
    z_2: { x: 0.0, y: 0.0, width: 50.0, height: 52.78 },
    z_3: { x: 0.0, y: 0.0, width: 47.22, height: 50.0 },
  },
} as const satisfies { textureScale: number; frames: Record<string, AtlasFrameData> };
